-- JOIN 실습
-- EMPLOYEE, DEPARTMENT를 조인해서 이름, 속한 부서명 조회
SELECT EMP_NAME, DEPT_TITLE FROM EMPLOYEE JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);
SELECT EMP_NAME, DEPT_TITLE FROM EMPLOYEE,DEPARTMENT WHERE DEPT_CODE = DEPT_ID;

-- EMPLOYEE, DEPARTMENT를 조인해서 이름, 부서명, 급여 조회
SELECT EMP_NAME, DEPT_TITLE, SALARY FROM EMPLOYEE JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);
SELECT EMP_NAME, DEPT_TITLE, SALARY FROM EMPLOYEE,DEPARTMENT WHERE DEPT_CODE = DEPT_ID;

-- EMPLOYEE, SAL_GRADE를 조인해서 이름, 급여등급 조회
SELECT EMPLOYEE.EMP_NAME, SAL_GRADE.SAL_LEVEL FROM EMPLOYEE JOIN SAL_GRADE ON (EMPLOYEE.SAL_LEVEL = SAL_GRADE.SAL_LEVEL);
-- 서로 다른 테이블에서 컬럼명은 다르지만 값이 같을 때는 (컬럼명1 = 컬럼명2) 사용할 수 있음
-- 서로 다른 테이블에서 컬럼명과 값이 모두 같을 때는 참조하는 테이블이 무엇인지 작성해줘야함
-- 테이블명.컬럼명1 = 테이블명.컬럼명2
-- SELECT로 참조할 때도 테이블명을 작성해서 어느 테이블에서 가져온 컬럼명인지 표기해줘야함
SELECT e.EMP_NAME, s.SAL_LEVEL FROM EMPLOYEE e,SAL_GRADE s WHERE e.SAL_LEVEL = s.SAL_LEVEL;

-- EMPLOYEE, DEPARTMENT, JOB에서 각 직원의 이름, 속한 부서명 및 직급 조회
-- ANSI
SELECT e.EMP_NAME, d.DEPT_TITLE, j.JOB_NAME FROM EMPLOYEE e 
JOIN DEPARTMENT d ON (e.DEPT_CODE = d.DEPT_ID)
JOIN JOB j ON (e.JOB_CODE = j.JOB_CODE);

-- ORACLE
SELECT E.EMP_NAME, D.DEPT_TITLE, J.JOB_CODE FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID AND E.JOB_CODE = J.JOB_CODE;

-- EMPLOYEE, DEPARTMENT에서 직원의 이메일 주소, 해당 부서의 부서명 조회
SELECT E.EMP_NAME, E.EMAIL, D.DEPT_TITLE FROM EMPLOYEE E JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID);
SELECT E.EMP_NAME, E.EMAIL, D.DEPT_TITLE FROM EMPLOYEE E, DEPARTMENT D WHERE E.DEPT_CODE = D.DEPT_ID;

-- EMPLOYEE, DEPARTMENT에서 급여가 300만원 이상인 직원의 이름, 속한 부서명
SELECT E.EMP_NAME, E.SALARY, D.DEPT_TITLE FROM EMPLOYEE E JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID) WHERE E.SALARY >= 3000000;
SELECT E.EMP_NAME, E.SALARY, D.DEPT_TITLE FROM EMPLOYEE E, DEPARTMENT D WHERE E.DEPT_CODE = D.DEPT_ID AND E.SALARY >= 3000000;

-- EMPLOYEE, DEPARTMENT, SAL_GRADE에서 직원의 이름, 속한 부서명, 급여 등급 조회
SELECT E.EMP_NAME, D.DEPT_TITLE, S.SAL_LEVEL FROM EMPLOYEE E, DEPARTMENT D, SAL_GRADE S 
WHERE E.DEPT_CODE = D.DEPT_ID AND E.SAL_LEVEL = S.SAL_LEVEL;

SELECT E.EMP_NAME, D.DEPT_TITLE, S.SAL_LEVEL FROM EMPLOYEE E 
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN SAL_GRADE S ON (E.SAL_LEVEL = S.SAL_LEVEL);

-- 직급이 대리이면서 아시아 지역에 근무하는 직원 조회
-- 사번 이름 직급명 부서명 근무지역명 급여
-- EMPLOYEE, JOB, DEPARTMENT, LOCATION
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, D.DEPT_TITLE, L.NATIONAL_CODE, E.SALARY
FROM EMPLOYEE E, JOB J, DEPARTMENT D, LOCATION L
WHERE E.DEPT_CODE = D.DEPT_ID AND E.JOB_CODE = J.JOB_CODE AND D.LOCATION_ID = L.LOCAL_CODE 
AND J.JOB_NAME = '대리' AND L.LOCAL_NAME LIKE 'ASIA%';

-- D5부서에 속한 직원들의 이름, 직급명
-- EMPLOYEE, JOB
SELECT EMP_NAME, JOB_NAME FROM EMPLOYEE JOIN JOB USING(JOB_CODE) WHERE DEPT_CODE = 'D5';

-- 각 부서의 부서명, 해당 부서의 평균 급여
-- EMPLOYEE, DEPARTMENT
SELECT DEPT_TITLE, FLOOR(AVG(SALARY)) FROM EMPLOYEE JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID) group by DEPT_TITLE ORDER BY DEPT_TITLE;

-- 급여 등급이 S4 이상인 직원의 이름, 급여, 급여 등급 조회
-- EMPLOYEE, SAL_GRADE
SELECT EMP_NAME, SALARY, SAL_LEVEL FROM EMPLOYEE JOIN SAL_GRADE USING(SAL_LEVEL) WHERE SAL_LEVEL IN ('S4','S5','S6');






