-- CREATE TABLE 실습

-- 고객 테이블 CUSTOMER
CREATE TABLE CUSTOMER (
    CUSTOMER_ID NUMBER(10,0) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    CUSTOMER_EMAIL VARCHAR2(100) CONSTRAINT C_E_U UNIQUE,
    CUSTOMER_PHONE VARCHAR2(20), 
    CUSTOMER_ADDRESS VARCHAR2(255),
    
    CONSTRAINT C_P_U UNIQUE(CUSTOMER_PHONE)
);
COMMENT ON COLUMN CUSTOMER.CUSTOMER_ID IS '고객 아이디';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_NAME IS '고객 이름';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_EMAIL IS '고객 이메일';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_PHONE IS '고객 휴대폰 번호';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_ADDRESS IS '고객 주소';
/*
테이블 이름에 큰 따옴표를 넣어도 문제가 없지만 큰 따옴표의 경우 대소문자를 구분하기 때문에 에러가 발생할 수 있음
*/
COMMIT;

-- PRODUCT 테이블 생성
CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER(10,0) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_PRICAE NUMBER(10,2) NOT NULL,
    PRODUCT_DESC VARCHAR2(200) CONSTRAINT PRODUCT_DESC_U UNIQUE
);

INSERT INTO PRODUCT VALUES (1, '아메리카노', '3000', '신선한 원두로 만든 아메리카노');
INSERT INTO PRODUCT VALUES (2, '카페라떼', '2500', '부드러운 우유가 들어간 라떼');
INSERT INTO PRODUCT VALUES (3, '카푸치노', '3500', '진한 커피와 거품이 어우러진 카푸치노');
INSERT INTO PRODUCT VALUES (4, '카라멜 마키아토', '4000', '달콤한 카라멜 시럽이 들어간 마키아토');

COMMIT;

-- FOOD_COMPANY 테이블 생성
CREATE TABLE FOOD_COMPANY(
    COMPANY_ID NUMBER(10,0) PRIMARY KEY,
    COMPANY_NAME VARCHAR2(100) NOT NULL,
    COMPANY_ADDRESS VARCHAR2(255),
    COMPANY_PHONE VARCHAR2(20)
);
-- SNACKS 테이블 생성
CREATE TABLE SNACKS (
    SNACK_ID NUMBER(10,0) PRIMARY KEY,
    SNACK_NAME VARCHAR2(100) NOT NULL,
    PRICE NUMBER(10,2) NOT NULL,
    COMPANY_ID NUMBER(10,0),
    CONSTRAINT FK_COMPANY FOREIGN KEY (COMPANY_ID)
    REFERENCES FOOD_COMPANY(COMPANY_ID) ON DELETE CASCADE
);
-- COMPANY_ID : FOREIGN KEY, 키를 참조할 변수명
-- 참조할 변수명의 규칙 : 모든 테이블을 통틀어서 동일한 이름을 쓸 수 없음

-- 테이블 생성 DRINK_COMPANY
CREATE TABLE DRINK_COMPANY(
    DRINK_ID NUMBER(10,0) PRIMARY KEY,
    DRINK_NAME VARCHAR2(100) NOT NULL,
    DRINK_ADDRESS VARCHAR2(255),
    DRINK_PHONE VARCHAR2(20)
);

CREATE TABLE SOFTS(
    SOFTS_ID NUMBER(10,0) PRIMARY KEY,
    SOFTS_NAME VARCHAR2(100) NOT NULL,
    PRICE NUMBER(10,2) NOT NULL,
    DRINK_ID NUMBER(10,0),
    CONSTRAINT FK_DRINK FOREIGN KEY (DRINK_ID)
    REFERENCES DRINK_COMPANY(DRINK_ID) ON DELETE CASCADE
);

INSERT INTO DRINK_COMPANY VALUES(1, '고가콜라', '서울시 강남구', '02-1234-5678');
INSERT INTO DRINK_COMPANY VALUES(2, '벱시', '서울시 중구', '02-8765-4321');

INSERT INTO SOFTS VALUES(1, '콜라', 1500, 1);
INSERT INTO SOFTS VALUES(2, '사이다', 1200, 1);
INSERT INTO SOFTS VALUES(3, '벱시콜라', 1000, 2);
INSERT INTO SOFTS VALUES(4, '마운틴듀오', 2000, 2);




